name: sync_dev_fork

on:
  push:
    branches:
      - "dev"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    if: ${{ github.event.repository.name == 'RodrigoSMarques/flutter_branch_sdk' }}
      - name: Show variables
        run: - run: echo ${{ github.event.repository.name }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.FORK_REPO_ACCESS_TOKEN}}
          repository: r-s-marques/flutter_branch_sdk
          event-type: commit-dev
