name: sync_dev_fork

on:
  push:
    branches:
      - "dev"

jobs:
  - name: Repository Dispatch
    uses: peter-evans/repository-dispatch@v2
    with:
      token: ${{ secrets.MY_GITHUB_TOKEN }}
      repository: r-s-marques/flutter_branch_sdk
      event-type: commit-dev