name: sync_dev_fork

on:
  push:
    branches:
      - "dev"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Show variables
        run: echo ${{ github.repository }}
        run: echo ${{ github.repository_owner }}
      - name: Repository Dispatch
        if: ${{ github.repository == 'RodrigoSMarques/flutter_branch_sdk' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.FORK_REPO_ACCESS_TOKEN}}
          repository: r-s-marques/flutter_branch_sdk
          event-type: commit-dev
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
      - run: echo ${{ github.event.client_payload.sha }}
