name: Publish plugin - pub.dev

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with: 
          environment: release
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Install dependencies
        run: dart pub get
      - name: Generate documenti
        run: dart doc
      - name: Publish flutter package
        run: flutter pub pub publish --dry-run
