name: Push File

on: 
  push:
    branches:
      - "dev"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create pull request
      uses: paygoc6/action-pull-request-another-repo@v1.0.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        source_folder: '.'
        destination_repo: 'r-s-marques/flutter_branch_sdk'
        destination_base_branch: 'dev'
        destination_head_branch: 'dev'
        user_email: 'rodrigosmarques@gmail.com'
        user_name: 'RodrigoSMarques'