name: Sync Branch MASTER into BUGFIX
on:
  push:
    branches:
    - "master"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2.6.2
      with:
        source_branch: "master"                           # If blank, default: triggered branch
        destination_branch: "bugfix"                         # If blank, default: master
        pr_title: "Sync Branch MASTER into BUGFIX" # Title of pull request
        pr_body: "👑 *An automated PR*"              # Full markdown support, requires pr_title to be set
        pr_label: "auto-pr"                               # Comma-separated list (no spaces)
        pr_draft: false                                    # Creates pull request as draft
        pr_allow_empty: false                              # Creates pull request even if there are no changes
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}